theme: minima
title: My awesome title
author: bruno
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec feugiat nisl pretium fusce id velit ut. Diam donec adipiscing tristique risus nec. Tellus mauris a diam maecenas sed. Nunc non blandit massa enim nec dui nunc mattis. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Orci porta non pulvinar neque.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
